import { useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AccountHeader, AccountScreen, sharedStyles as s } from './account/_shared';
import { useAuth } from '../src/hooks/useAuth';
import { authService } from '../src/services/authService';
import { Colors, Spacing } from '../src/constants/theme';

export default function AccountScreenPage() {
  const router = useRouter(); const { currentUser, logout } = useAuth(); const [expanded, setExpanded] = useState(false); const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const updatePassword = async () => { if (next.length < 6 || next !== confirm) return setError(next.length < 6 ? 'A nova senha deve ter pelo menos 6 caracteres.' : 'As senhas não coincidem.'); setLoading(true); setError(''); try { await authService.changePassword(currentUser!.id, current, next); setExpanded(false); setCurrent(''); setNext(''); setConfirm(''); Alert.alert('Senha atualizada', 'Sua senha foi alterada com sucesso.'); } catch { setError('Não foi possível atualizar a senha. Confira sua senha atual.'); } finally { setLoading(false); } };
  const deleteAccount = () => Alert.alert('Excluir Conta?', 'Esta ação apagará permanentemente todos os seus dados. Deseja continuar?', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Sim, Excluir', style: 'destructive', onPress: async () => { try { await authService.deleteAccount(currentUser!.id); await logout(); router.replace('/login'); } catch { Alert.alert('Erro', 'Não foi possível excluir sua conta.'); } } }]);
  return <AccountScreen><AccountHeader title="Minha Conta" onBack={() => router.back()} /><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled">
    <Text style={s.sectionTitle}>ACESSO</Text><View style={s.card}><Text style={s.label}>E-mail de Login</Text><TextInput style={[s.input, s.readOnly]} value={currentUser?.email ?? ''} editable={false} /><TouchableOpacity style={styles.link} onPress={() => { setExpanded(!expanded); setError(''); }}><Text style={styles.linkText}>{expanded ? 'Cancelar alteração' : 'Alterar Senha'}</Text></TouchableOpacity>{expanded && <View><Text style={s.label}>Senha Atual</Text><TextInput style={s.input} value={current} onChangeText={setCurrent} secureTextEntry textContentType="password" /><Text style={s.label}>Nova Senha</Text><TextInput style={s.input} value={next} onChangeText={setNext} secureTextEntry textContentType="newPassword" /><Text style={s.label}>Confirmar Nova Senha</Text><TextInput style={s.input} value={confirm} onChangeText={setConfirm} secureTextEntry textContentType="newPassword" />{!!error && <Text style={s.error}>{error}</Text>}<TouchableOpacity style={s.primary} onPress={updatePassword} disabled={loading}>{loading ? <ActivityIndicator color="#FFF" /> : <Text style={s.primaryText}>Atualizar Senha</Text>}</TouchableOpacity></View>}</View>
    <View style={styles.dangerZone}><Text style={[s.sectionTitle, { color: Colors.danger }]}>ZONA DE PERIGO</Text><Text style={s.muted}>A exclusão da conta não pode ser desfeita.</Text><TouchableOpacity style={styles.delete} onPress={deleteAccount}><Text style={styles.deleteText}>Excluir minha conta</Text></TouchableOpacity></View>
  </ScrollView></KeyboardAvoidingView></AccountScreen>;
}
const styles = { link: { minHeight: 44, justifyContent: 'center', marginTop: Spacing.md } as const, linkText: { color: Colors.accent, fontFamily: 'PlusJakartaSans_600SemiBold' } as const, dangerZone: { marginTop: 56 } as const, delete: { minHeight: 52, borderWidth: 1, borderColor: Colors.danger, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginTop: Spacing.lg } as const, deleteText: { color: Colors.danger, fontFamily: 'PlusJakartaSans_700Bold' } as const };
