import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { AccountHeader, AccountScreen, sharedStyles as s } from './account/_shared';
import { UserAvatar } from './components/account/UserAvatar';
import { useAuth } from '../src/hooks/useAuth';
import { authService } from '../src/services/authService';
import { onboardingService } from '../src/services/onboardingService';
import { photoService } from '../src/services/photoService';
import { businessStateService } from '../src/services/businessStateService';
import { useAppStore } from '../src/store';
import { Colors, FontSize, Radius, Spacing } from '../src/constants/theme';

type Editing = 'personal' | 'business' | 'password' | null;
export default function ProfileScreen() {
  const router = useRouter(); const { currentUser, updateUser, refreshUser, logout } = useAuth(); const businessName = useAppStore(x => x.businessName); const businessType = useAppStore(x => x.businessType); const updateBusinessDetails = useAppStore(x => x.updateBusinessDetails);
  const [savingPhoto, setSavingPhoto] = useState(false);
  const [deletePassword, setDeletePassword] = useState('');
  const [deleting, setDeleting] = useState(false);
  const deleteAccount = () => { if (!currentUser || !deletePassword || deleting) return; Alert.alert('Excluir conta definitivamente?', 'Seus dados e sua foto serão removidos. Esta ação não pode ser desfeita.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: async () => { setDeleting(true); try { await authService.deleteAccount(currentUser.id, deletePassword); await logout().catch(() => {}); router.replace('/welcome'); } catch (cause) { Alert.alert('Erro', cause instanceof Error ? cause.message : 'Não foi possível excluir a conta.'); } finally { setDeleting(false); } } }]); };
  const uploadPhoto = async () => { if (savingPhoto) return; setSavingPhoto(true); try { const url = await photoService.pickAndUpload(); if (url) await refreshUser(); } catch (cause) { Alert.alert('Foto', cause instanceof Error ? cause.message : 'Não foi possível salvar a foto.'); } finally { setSavingPhoto(false); } };
  const [editing, setEditing] = useState<Editing>(null); const [name, setName] = useState(''); const [role, setRole] = useState(''); const [phone, setPhone] = useState(''); const [businessNameDraft, setBusinessNameDraft] = useState(''); const [businessTypeDraft, setBusinessTypeDraft] = useState(''); const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { setName(currentUser?.name ?? ''); setRole(currentUser?.role ?? ''); setPhone(currentUser?.phone ?? ''); }, [currentUser]);
  useEffect(() => { setBusinessNameDraft(businessName); setBusinessTypeDraft(businessType); }, [businessName, businessType]);
  const cancel = () => { setEditing(null); setError(''); setName(currentUser?.name ?? ''); setRole(currentUser?.role ?? ''); setPhone(currentUser?.phone ?? ''); setBusinessNameDraft(businessName); setBusinessTypeDraft(businessType); setCurrent(''); setNext(''); setConfirm(''); };
  const savePersonal = async () => { if (!name.trim()) return setError('Informe seu nome para continuar.'); setSaving(true); setError(''); try { await updateUser({ name, role, phone }); setEditing(null); Alert.alert('Dados atualizados', 'Suas informações foram salvas.'); } catch { setError('Não foi possível salvar agora. Tente novamente.'); } finally { setSaving(false); } };
  const saveBusiness = async () => { if (!businessNameDraft.trim()) return setError('Informe o nome do negócio para continuar.'); if (!currentUser) return; setSaving(true); setError(''); try { const nextName = businessNameDraft.trim(); const nextType = businessTypeDraft.trim(); updateBusinessDetails(nextName, nextType); await businessStateService.commit(); const state = useAppStore.getState(); await onboardingService.saveStructuredProfile(currentUser.id, state.onboardingExtraction ? { ...state.onboardingExtraction, taxonomy: state.taxonomy } : state.taxonomy); setEditing(null); Alert.alert('Negócio atualizado', 'Nome e ramo foram salvos sem refazer sua configuração inicial.'); } catch { setError('Não foi possível salvar agora. Tente novamente.'); } finally { setSaving(false); } };
  const savePassword = async () => { if (next.length < 6) return setError('A nova senha deve ter pelo menos 6 caracteres.'); if (next !== confirm) return setError('As senhas não coincidem.'); if (!currentUser) return; setSaving(true); setError(''); try { await authService.changePassword(currentUser.id, current, next); cancel(); Alert.alert('Senha atualizada', 'Sua senha foi alterada com sucesso.'); } catch { setError('Não foi possível atualizar a senha. Confira os dados e tente novamente.'); } finally { setSaving(false); } };
  const personalEdit = editing === 'personal'; const businessEdit = editing === 'business'; const passwordEdit = editing === 'password';
  return <AccountScreen><AccountHeader title="Perfil e configurações" onBack={() => router.back()} /><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}>
    <View style={styles.hero}><TouchableOpacity onPress={uploadPhoto} disabled={savingPhoto} accessibilityRole="button" accessibilityLabel="Alterar foto de perfil">{savingPhoto ? <ActivityIndicator color={Colors.accent} /> : <UserAvatar user={currentUser} size={72} />}</TouchableOpacity><View style={styles.heroText}><Text style={styles.name}>{currentUser?.name || 'Seu perfil'}</Text><Text style={styles.email}>{currentUser?.email}</Text><Text style={styles.email}>Toque na foto para alterar</Text></View></View>
    <Section title="SEUS DADOS" icon="person-outline" action={!personalEdit ? () => { setEditing('personal'); setError(''); } : undefined} actionLabel="Editar">{personalEdit ? <><Field label="Nome" value={name} onChangeText={setName} autoCapitalize="words" /><Field label="Cargo ou função" value={role} onChangeText={setRole} placeholder="Ex.: Proprietário" /><Field label="Telefone" value={phone} onChangeText={setPhone} placeholder="(00) 00000-0000" keyboardType="phone-pad" /><Text style={styles.hint}>Seu e-mail de acesso não pode ser alterado por aqui.</Text>{!!error && <Text style={s.error}>{error}</Text>}<Actions saving={saving} onCancel={cancel} onSave={savePersonal} label="Salvar dados" /></> : <><Detail label="Nome" value={currentUser?.name || 'Não informado'} /><Detail label="Cargo ou função" value={currentUser?.role || 'Não informado'} /><Detail label="Telefone" value={currentUser?.phone || 'Não informado'} /><Detail label="E-mail de acesso" value={currentUser?.email || ''} /></>}</Section>
    <Section title="SEU NEGÓCIO" icon="storefront-outline" action={!businessEdit ? () => { setEditing('business'); setError(''); } : undefined} actionLabel="Editar">{businessEdit ? <><Field label="Nome do negócio" value={businessNameDraft} onChangeText={setBusinessNameDraft} autoCapitalize="words" /><Field label="Ramo ou segmento" value={businessTypeDraft} onChangeText={setBusinessTypeDraft} placeholder="Ex.: Serviços de instalação" autoCapitalize="words" /><Text style={styles.hint}>Isso atualiza só a identificação do seu negócio. Categorias, módulos e recomendações atuais permanecem como estão.</Text>{!!error && <Text style={s.error}>{error}</Text>}<Actions saving={saving} onCancel={cancel} onSave={saveBusiness} label="Salvar negócio" /></> : <><Detail label="Nome do negócio" value={businessName || 'Não informado'} /><Detail label="Ramo ou segmento" value={businessType || 'Não informado'} /></>}</Section>
    <Section title="SEGURANÇA" icon="shield-checkmark-outline" action={!passwordEdit ? () => { setEditing('password'); setError(''); } : undefined} actionLabel="Alterar senha">{passwordEdit ? <><Field label="Senha atual" value={current} onChangeText={setCurrent} secureTextEntry textContentType="password" /><Field label="Nova senha" value={next} onChangeText={setNext} secureTextEntry textContentType="newPassword" /><Field label="Confirmar nova senha" value={confirm} onChangeText={setConfirm} secureTextEntry textContentType="newPassword" />{!!error && <Text style={s.error}>{error}</Text>}<Actions saving={saving} onCancel={cancel} onSave={savePassword} label="Atualizar senha" /></> : <Text style={styles.copy}>Mantenha sua senha atualizada para proteger o acesso ao Lumio.</Text>}</Section>
    <Section title="RECURSOS" icon="sparkles-outline"><TouchableOpacity style={styles.resource} onPress={() => router.push('/ai-settings')} accessibilityRole="button"><View style={styles.resourceIcon}><Ionicons name="sparkles" size={18} color={Colors.accent} /></View><View style={{ flex: 1 }}><Text style={styles.resourceTitle}>Inteligência Artificial</Text><Text style={styles.resourceCopy}>Gerencie sua chave do Google Gemini na sua conta.</Text></View><Ionicons name="chevron-forward" size={18} color={Colors.textMuted} /></TouchableOpacity></Section>
    <Section title="EXCLUIR CONTA" icon="trash-outline"><Text style={styles.copy}>Digite sua senha para excluir sua conta e seus dados definitivamente.</Text><Field label="Senha atual" value={deletePassword} onChangeText={setDeletePassword} secureTextEntry textContentType="password" /><TouchableOpacity onPress={deleteAccount} disabled={!deletePassword || deleting} style={{ alignItems: 'center', padding: Spacing.lg, opacity: !deletePassword || deleting ? 0.5 : 1 }}><Text style={{ color: Colors.danger }}>{deleting ? 'Excluindo...' : 'Excluir minha conta'}</Text></TouchableOpacity></Section>
  </ScrollView></KeyboardAvoidingView></AccountScreen>;
}
function Section({ title, icon, action, actionLabel, children }: { title: string; icon: any; action?: () => void; actionLabel?: string; children: React.ReactNode }) { return <View style={styles.section}><View style={styles.sectionHead}><View style={styles.titleGroup}><Ionicons name={icon} size={17} color={Colors.accent} /><Text style={s.sectionTitle}>{title}</Text></View>{action && <TouchableOpacity onPress={action} style={styles.editButton}><Text style={styles.editText}>{actionLabel}</Text></TouchableOpacity>}</View><View style={s.card}>{children}</View></View>; }
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }
function Field(props: any) { const { label, ...input } = props; return <><Text style={s.label}>{label}</Text><TextInput style={s.input} {...input} placeholderTextColor={Colors.textMuted} /></>; }
function Actions({ saving, onCancel, onSave, label }: { saving: boolean; onCancel: () => void; onSave: () => void; label: string }) { return <View style={styles.actions}><TouchableOpacity onPress={onCancel} style={styles.cancel} disabled={saving}><Text style={styles.cancelText}>Cancelar</Text></TouchableOpacity><TouchableOpacity onPress={onSave} style={[styles.save, saving && { opacity: .7 }]} disabled={saving}>{saving ? <ActivityIndicator color="#FFF" /> : <Text style={s.primaryText}>{label}</Text>}</TouchableOpacity></View>; }
const styles = StyleSheet.create({ hero: { flexDirection: 'row', alignItems: 'center', gap: Spacing.lg, backgroundColor: Colors.bgCard, borderRadius: Radius.lg, padding: Spacing.lg }, heroText: { flex: 1 }, name: { color: Colors.primary, fontFamily: 'PlusJakartaSans_700Bold', fontSize: FontSize.lg }, email: { color: Colors.textSecondary, fontSize: FontSize.sm, marginTop: 4 }, section: { marginTop: Spacing.xxl }, sectionHead: { minHeight: 27, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.sm }, titleGroup: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs }, editButton: { minHeight: 36, justifyContent: 'center', paddingHorizontal: Spacing.sm }, editText: { color: Colors.accent, fontFamily: 'PlusJakartaSans_700Bold', fontSize: FontSize.sm }, detail: { paddingVertical: Spacing.sm, borderBottomWidth: 1, borderBottomColor: Colors.border }, detailLabel: { color: Colors.textMuted, fontSize: FontSize.xs, marginBottom: 3 }, detailValue: { color: Colors.primary, fontFamily: 'PlusJakartaSans_500Medium', fontSize: FontSize.md }, hint: { color: Colors.textSecondary, fontSize: FontSize.xs, lineHeight: 18, marginTop: Spacing.lg }, actions: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.xl }, cancel: { flex: 1, minHeight: 50, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center' }, cancelText: { color: Colors.textSecondary, fontFamily: 'PlusJakartaSans_700Bold' }, save: { flex: 1.5, minHeight: 50, borderRadius: Radius.md, backgroundColor: Colors.accent, justifyContent: 'center', alignItems: 'center' }, copy: { color: Colors.textSecondary, fontSize: FontSize.sm, lineHeight: 20 }, resource: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, minHeight: 54 }, resourceIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.accentLight, alignItems: 'center', justifyContent: 'center' }, resourceTitle: { color: Colors.primary, fontFamily: 'PlusJakartaSans_600SemiBold', fontSize: FontSize.md }, resourceCopy: { color: Colors.textSecondary, fontSize: FontSize.xs, marginTop: 3 } });
