import {
  Colors,
  FontSize,
  Radius,
  Spacing,
} from "../../../src/constants/theme";
import { taskFormStyles } from "../Tasks/taskFormStyles";

// Shared visual language for CRUD forms opened from plugin screens.
export const pluginFormStyles: Record<string, any> = {
  ...taskFormStyles,
  modalOverlay: {
    width: "100%" as const,
  },
  overlay: {
    width: "100%" as const,
  },
  modalCard: {
    width: "100%" as const,
    maxHeight: "100%" as const,
    backgroundColor: "transparent",
    borderRadius: 0,
    padding: 0,
    gap: Spacing.xs,
    flexShrink: 1,
  },
  modal: {
    width: "100%" as const,
    maxHeight: "100%" as const,
    backgroundColor: "transparent",
    borderRadius: 0,
    padding: 0,
    gap: Spacing.xs,
    flexShrink: 1,
  },
  modalTitle: taskFormStyles.title,
  label: taskFormStyles.label,
  fieldLabel: taskFormStyles.label,
  input: taskFormStyles.input,
  modalActions: taskFormStyles.actions,
  actions: taskFormStyles.actions,
  modalCancel: taskFormStyles.cancelBtn,
  cancel: taskFormStyles.cancelBtn,
  modalCancelText: taskFormStyles.cancelBtnText,
  cancelText: taskFormStyles.cancelBtnText,
  modalConfirm: taskFormStyles.saveBtn,
  saveButton: taskFormStyles.saveBtn,
  modalConfirmText: taskFormStyles.saveBtnText,
  saveText: taskFormStyles.saveBtnText,
  confirm: taskFormStyles.saveBtn,
  confirmText: taskFormStyles.saveBtnText,
  chip: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 5,
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgCard,
  },
  chipActive: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  chipText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: FontSize.xs,
    color: Colors.textSecondary,
  },
  chipTextActive: { color: "#FFFFFF" },
  selectChip: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 5,
    paddingHorizontal: Spacing.md,
    paddingVertical: 6,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgCard,
  },
  selectChipActive: { backgroundColor: Colors.accent, borderColor: Colors.accent },
  selectChipText: {
    fontFamily: "PlusJakartaSans_500Medium",
    fontSize: FontSize.xs,
    color: Colors.textSecondary,
  },
  selectChipTextActive: { color: "#FFFFFF" },
};
